### ISSUE TITLE
Breaks touch scroll on touch devices.

### ISSUE THREAD

**Issue by plamenh** [theKashey/react-remove-scroll-bar#2]
Title says it all. Page becomes unresponsive on mobile devices.

**Comment by theKashey** [comment]
I reckon - on Android.
Also it breaks wheel scroll for desktop browsers.

That's intentional - this library is a submodule for `react-remove-scroll`/`react-focus-on` and others.

If you need just to hide scroll - try [react-stroller](https://github.com/theKashey/React-stroller) with no `Bar` set.
