### ISSUE TITLE
Doesnt work unless specifying height: 100vh on body

### ISSUE THREAD

**Issue by mrGibi** [theKashey/react-remove-scroll-bar#3]
Hi,

I couldn't get this component to work unless I set a `height: 100vh` on body, but then, when `<RemoveScrollBar />` loads, the page scrolls to the top.
Any advice? 

Thanks

**Comment by theKashey** [comment]
Have no idea, especially about scrolling to the top. Could you provide any example?

**Comment by mrGibi** [comment]
My bad. I loaded something similar to css reset/normalize which turns out set a `html { overflow-y: scroll }`. Once I `unset` it, Your component works as it should.
Sorry for bothering ;)

**Comment by theKashey** [comment]
Happy coding.
