### ISSUE TITLE
Better explanation of how it should work

### ISSUE THREAD

**Issue by ezhlobo** [theKashey/react-remove-scroll-bar#31]
I got the issue with this package and I tried to figure out how it's supposed to be used properly. 

To debug my issue and figure out options I created this snippet that sets different values of `padding` and `margin` to `<body>` and with different `gapMode`: https://codesandbox.io/s/remove-scroll-bar-i7obpk

It seems for me like it works not very stable with `gapMode=margin`. With `padding` mode it seems more robust, but doesn't take into account previous value.

I'd be happy to help and make it handling all those cases, but I expect there are more of them. So if you can help me with more use cases I'd be able to help you coding the fix. Alternatively I'd expect some documentation of what this package expect to be set over `<body>` to keep it working.

**Comment by theKashey** [comment]
I am still trying to remember why margin was picked over padding, and believe me - I’ve spend a few months playing around it (now I remember it)

but so far the best (but not good) source of information for me is my younger me - https://medium.com/react-camp/how-to-fight-the-body-scroll-2b00267b37ac
