### ISSUE TITLE
Body jumping when padding is not 0

### ISSUE THREAD

**Issue by xavier-kairn** [theKashey/react-remove-scroll-bar#33]
Hello @theKashey, I have what I think is a similar issue to #31: when the padding of the body is not 0 and the `gapMode` is `margin`, then the body "jumps" when the component works its magic to remove the scrollbars.

For some more details, I use this library through radix-ui. I originally posted [a comment there](https://github.com/radix-ui/primitives/issues/1548#issuecomment-1191266151), and was redirected here.

From what I understand of your Medium post, it's better to use a margin gap mode to avoid jitters and jumps from the body. However, when the body has a padding, then it does jump up when mounting the scrollbar remover. The thing is, I am using your component via radix-ui inside a Chrome extension, which means:
- not having a padding on the body is not really an option for me
- I cannot easily change the gapMode

For a quick example: https://codesandbox.io/s/vigilant-bird-1fj6og?file=/src/App.tsx

Trying to patch `react-remove-scroll-bar` locally, I have found that adding the padding and margin instead of selecting only one [on these lines](https://github.com/theKashey/react-remove-scroll-bar/blob/master/src/utils.ts#L30-L32) solves my issue.

I have found other ways to solve my issue, such as patching `@radix-ui/react-popover` so that it passes `removeScrollBar={false}` to `react-remove-scroll`, but I am wondering what is the best way forward between the 2 patches. Do you have a recommendation? Do you know if maybe adding the padding and margin as I mention above is a valid fix?

**Comment by theKashey** [comment]
I would say that in this particular case this is a __bug__ on remove-scroll side which should be solve as a part of https://github.com/theKashey/react-remove-scroll/issues/73 - there are __situations when no action__ should be taken by the library.
