### ISSUE TITLE
Console error "cannot calculate scrollbar size because it is removed"

### ISSUE THREAD

**Issue by raymond-shanley-dynatrace** [theKashey/react-remove-scroll-bar#35]
When an app XYZ is using a library that in turn is using `react-remove-scroll-bar `and at the same time, the XYZ app has the scrollbar removed for a different reason that can't be avoided.

So the app has something like the following:

`<body style="overflow: hidden;">`

Then a `console.error `is logged in the console.

Can we avoid logging this error?

**Comment by explorador** [comment]
[This](https://github.com/theKashey/react-remove-scroll-bar/commit/3a6aafd1388d1b52ccd1bf7db2a14a15cddf1680) is the commit that added this message. @theKashey what's the purpose of this? Thanks for your help!

**Comment by theKashey** [comment]
The error message is displayed only during development and should cause any trouble for a real customer, and I can replace the error with a warning if that would work for you.

The change itself was a fix for https://github.com/theKashey/react-remove-scroll/issues/71 (issues are often raised for library consumers) and logging was added to reduce "wtf per minute" - the most important metric I have.

**Comment by explorador** [comment]
Makes sense. I think a warning is more fitting too. Thanks for your help!

**Comment by hixus** [comment]
Not completely aware how react-remove-scroll-bar does it's magic but should it somehow track with css class or something that it actually has already hidden the scrollbar? Then it would not matter if react-remove-scroll-bar would be initialised multiple times.

**Comment by theKashey** [comment]
It tracks "own" classes but is not able to handle third-party ones. Can only report an issue

**Comment by saradevh** [comment]
@theKashey Hi! Do you still plan to update the error with a warning? Thanks

**Comment by theKashey** [comment]
Absolutely.

**Comment by hixus** [comment]
> It tracks "own" classes but is not able to handle third-party ones. Can only report an issue

No I mean if react-remove-scroll-bar component is mounted twice each of them executes getGapWidth => getOffset which has the error mentioned in this ticket. And the latter will always fail as  react-remove-scroll-bar itself sets body as overflow hidden

**Comment by kof** [comment]
It would make sense to allow disabling that warning, because I have overflow: hidden on body and having that warning on every interaction with radix-ui components. It's a transitive dependency for me, so I would need a way to disable it from "outside".

**Comment by theKashey** [comment]
> No I mean if react-remove-scroll-bar component is mounted twice each of them executes getGapWidth => getOffset which has the error mentioned in this ticket.

😕 this should not happen, and that's definitely a bug.
Let's address this in a simple way - completely removing noise now and thinking about better ways to expose potential problems with calculations later.

**Comment by theKashey** [comment]
Particularly this issue has been resolved. 
You need to update to version 2.3.4, I am also going to publish v2.4.0 in a few hours to address other upstanding issues.
----
Version update propagation might take a while and if you need results here and now - you will need to find `react-remove-scroll-bar` in your lock file and update(remove) the corresponding record to let your package manager install a fresh version.

`Yarn` users can do `npx yarn-unlock-file all --only "react-remove-scroll-bar"` followed by `yarn` to perform a simular operation without manual intervention.
