### ISSUE TITLE
Restore body scroll position

### ISSUE THREAD

**Issue by receter** [theKashey/react-remove-scroll-bar#4]
By setting `overflow: hidden` to the body the current scroll position gets reset to 0.

I suggest to remember the body scroll position on mounting (`const scrollX = window.scrollX, const scrollY = window.scrollY`) and restore it afterwards with window.scroll(scrollX, scrollY);

Further you could call `window.scroll()` after `overflow: hidden` is applied and so immediately scroll to the initial scroll position while maintaining `overflow: hidden` (at least this seems to work in FF).

What do you think?

**Comment by theKashey** [comment]
Just checked it again - no, scroll position is not lost on `overflow: hidden`. 
Do you have an example to play with?

**Comment by receter** [comment]
You are right, I assumed is is `overflow: hidden` that resets my scroll, but it must be something else. I will go find out what happended, post my issue here and close this. Thanks!

**Comment by theKashey** [comment]
👍

**Comment by receter** [comment]
My issue was that I had a component that does `window.scrollTo(0, 0)` for every location change. And because I showed a modal in response to a location change it reset the scroll position.
