### ISSUE TITLE
Space for scroll bar remains when changing route

### ISSUE THREAD

**Issue by nt294** [theKashey/react-remove-scroll-bar#44]
I am using React Router to render different pages on my app. Page 1 has a scroll bar, and Page 2 is using this module to remove it. When I navigate from Page 1 to Page 2, there is a blank area where the scroll bar was that the application does not fill, despite being set to use 100% width. If I refresh and load the application directly from Page 2, this phantom area does not display and the page takes up 100% of the width as intended.

**Comment by theKashey** [comment]
Really not sure about this use case. Can you at least record a video?
