### ISSUE TITLE
Using `RemoveScrollBar` causes reevaluate off page css

### ISSUE THREAD

**Issue by fiws** [theKashey/react-remove-scroll-bar#54]
We are using radix components which use this library internally.

I think radix renders `<RemoveScrollBar />` in the head which causes the browser to reevaluate the css. I think this is the case, because we have a custom font included using `@font-face` and opening  an overlay (for example) causes the font to be requested **every time**. 
[dev tools screenshot](https://github.com/theKashey/react-remove-scroll-bar/assets/3409958/92f41c2b-c96e-4bc9-9711-91bc97533d0f) (this is me just opening and closing the overlay. Note that there also is some kind of race condition in chrome, it is not 100% reproducible)

The font is cached, but this sometimes causes flickering in firefox. If i'm correct then this also is not optimal performance wise because of the extra work the browser does.

Possible fix:
Do not dynamically add CSS. Always include css that only conditionally hides the scroll bar. Eg. when adding a class `hide-scollbar` to the body element

---

i can also create the issue in the radix repo instead, but i think this might be a problem with this library?

**Comment by theKashey** [comment]
This is a long story about the way font works in browser, and there are a lot of nuances here.
Please follow to https://github.com/styled-components/styled-components/issues/1593#issuecomment-486391047 for a "proper" solution. In short - you need to specify a proper caching for fonts and look like have them in a separate static css file.

> Possible fix: Do not dynamically add CSS

Technically speaking this will solve the problem. However it will cause the problem on application first render, plus it will cause a constant side effect of this package adding it styles while it's not used.
Both these moments are highly undesirable. Let's not do that.

Another possible fix could be in not using style sheets, but set inline styles to the body - it will work without any side effects including font invalidation.
The only way why it's not working this way today - a potential interference with other styles on the body, so sheets were picked as more fail-proof one. However I think solutions like Radix can easily afford direct style manipulation as they more or less control the "environment".
Still, the operational model should be up to consumer to decide.

**Comment by theKashey** [comment]
Another interestion option - change the API used underneath, as `insertRule` was reported to cause less side effects - https://github.com/styled-components/styled-components/issues/400#issuecomment-274961380

**Comment by theKashey** [comment]
Still important
