### ISSUE TITLE
Should `react-style-singleton` be a peer dependency instead?

### ISSUE THREAD

**Issue by jgarplind** [theKashey/react-remove-scroll-bar#72]
I did a bundle analysis using https://sonda.dev/ and found that I had `react-style-singleton` installed twice.

Digging into it, I could trace it back to me being dependent on `@radix-ui/react-menu`, which depends on `react-remove-scroll`, which in turn depends on both `react-remove-scroll-bar` and `react-style-singleton`, where the former (`react-remove-scroll-bar`) _also_ depends on `react-style-singleton`. This results in double entries of `react-style-singleton` in `node_modules`, one entry under `react-remove-scroll`'s `node_modules`, and one under `react-remove-scroll-bar`'s.

Given these libraries impressive amount of downloads, it would actually have a non-trivial impact to shave off the duplicated 300b, but I can also see how you might find it troublesome to impose a breaking change for those using `react-remove-scroll-bar` without `react-remove-scroll`.

I'm not sure how you view those trade-offs, but just wanted to make you aware that there is a possibility to make a small improvement for a million users.

P.S. I'm no bundling expert, but I can observe the real issue of the duplicated dependencies, and believe that peer dependencies should be a valid solution.

**Comment by theKashey** [comment]
If somebody needs a dependency is shall be a dependency. React is a very rare exclusing as it plays as "environment pre-requisition" and _started_ as peer dependency to enforce it's singlentone nature.

It's absolutely ok for two different packages depend on another one and it should not cause dependency dupliucation or how it called, a "doppelhanger". It only should happen when version ranges do not overlap.

In case of these two libraries the version range is the same and duplication can only be caused by someone else depending on a different major.

**Comment by jgarplind** [comment]
> In case of these two libraries the version range is the same and duplication can only be caused by someone else depending on a different major.

I thought so too, but in the end there is a duplicate in my `node_modules` (installed using `pnpm`), and there is only 1 version being referenced, and it's all from `@radix-ui`.

If you have any interest in investigating I can look into providing a minimum reproduction. FYI, in a repo of mine with 100s of dependencies, this is 1 of only 2 packages which has this "duplication issue".

**Comment by theKashey** [comment]
pnpm can "duplicate" dependencies, but there will actually be just one of them. It's _powerusing_ symlinks.
If you can verify the presence of duplication in the final bundle - that would be a problem to solve.

**Comment by jgarplind** [comment]
Might be relevant input that I'm using `node-linker=hoisted` as documented here: https://pnpm.io/npmrc#node-linker since there is a React Native app in my monorepo. The resulting structure is a single `node_modules` in the root, which has duplicate folders.

I admit that we are nearing edge case territory considering most probably use pnpm as is, and plausibly this is something that pnpm may be interested in handling better, rather than putting the burden on library authors. Is that aligned with your thinking?

**Comment by theKashey** [comment]
The "hoisted" is the most _default_ mode for `pnpm`, citing the docs - "Same as the node_modules created by npm or Yarn Classic"

If there is a duplicate folders there, then there should be a reason for such duplication, ie incompatible majors.
There are two possible cases:
- there are TREE `react-style-singleton` folders
  - one used by the app, sitting at top level with the "incompatible major"
  - one in each consumer (`react-remove-scroll-bar` and `react-remove-scroll-bar`)
-  there are TWO folders
  - one at the top level used by `react-remove-scroll-bar` OR `react-remove-scroll-bar`
  - and another one inside `react-remove-scroll-bar` OR `react-remove-scroll-bar`
  
There should be no case when without a copy at the top level. And the duplication can only be caused if that copy cannot be reused by another package. 

➡️ Look for a reason.

In no circumstances this problem can be solved by the library itself.

> But you can look at solution similar to https://github.com/atlassian-labs/webpack-deduplication-plugin, which can deduplicate the end bundle. And that is only thing that really matters.

**Comment by jgarplind** [comment]
Trying to reproduce using a simplified example, I was not able to.

Rather than spilling more time here (which I initiated, sorry for requesting your engagement in a half-baked issue), I will go forth and mark this as completed/not planned, and want to thank you for taking the time to clarify things.
